### ISSUE TITLE
How to use Pre-Selected Queues

### ISSUE THREAD

**Issue by leegalan** [haircut/self-service-printer-installer#2]
Hello,

Thank you so much for making this script. It does make it easier for our users. I wanted to start using the Pre-Selected Queue option. I put the Display Name from my printers.csv file in the policy field, but it gives me errors when I do that. How do I go about using this option properly? Thanks again,

Leeroy

**Comment by haircut** [comment]
Hi Leeroy,

Can you provide an example of the error(s) you're seeing?

The setup should be pretty straightforward; simply pass the queue name as "Parameter 4" to the generated Python script (i.e. the one you add to your JSS).

<img width="847" alt="screen shot 2019-01-04 at 6 15 06 pm" src="https://user-images.githubusercontent.com/3910/50715765-b9aa1080-104c-11e9-8063-34db5348be26.png">

(Here, I've renamed Parameter 4 to be a bit more user-friendly.)

It sounds like you're doing the same, so specificity with the error(s) you're seeing will help. Most illuminating would be the JSS policy log from a failed run.

Thanks,

**Comment by leegalan** [comment]
Hello, I've included a screenshot of the results I was seeing in the policy logs. Does the name you put in the policy script parameter #4, the one you call "Queue" in your screenshot, does that correspond to the DisplayName column in the printers.csv folder?

![screen shot 2019-01-07 at 10 56 42 am](https://user-images.githubusercontent.com/30468022/50778203-5ba74400-126b-11e9-975a-d870d93f08ab.png)

Thanks so much for helping.

Leeroy

**Comment by haircut** [comment]
Hm, that looks more like cocoaDialog is not installed on the system. The script should do better error checking there, certainly!

Do you have cocoaDialog installed on the system showing this error?

**Comment by leegalan** [comment]
Hi Matthew,

I may have shared the wrong one. I did fix the cocoaDialog issue. Check out this error:

![screen shot 2019-01-07 at 1 35 01 pm](https://user-images.githubusercontent.com/30468022/50786285-1b52c080-1281-11e9-819a-7c193eecf44f.png)
